"""empty message

Revision ID: a1aeea43bee8
Revises: 1068c2b96111
Create Date: 2025-04-02 16:38:48.548858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aeea43bee8'
down_revision = '1068c2b96111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=160), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
